apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 405d8112-4aac-4ef4-9918-dd135d272205
  labels:
    azure.workload.identity/use: "true"
  name: workload-identity-sa
  namespace: app-07
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-access # needs to be unique per namespace
  namespace: app-07
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: 405d8112-4aac-4ef4-9918-dd135d272205  # Setting this to use workload identity
    keyvaultName: aks-kv-465        # Set to the name of your key vault
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: application
          objectType: secret  # object types: secret, key, or cert
          objectVersion: ""   # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: title
          objectType: secret  # object types: secret, key, or cert
          objectVersion: ""   # [OPTIONAL] object versions, default to latest if empty          
    tenantId: "6ff1cfba-fc8f-44ff-9478-5e312195584d" # The tenant ID of the key vault 
  secretObjects: # k8s secret
  - secretName: secret
    type: Opaque
    data: 
    - objectName: title
      key: secret   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: app-07
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: aks-helloworld-two
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          valueFrom:
            secretKeyRef:
              name: secret
              key: secret
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/opt"
          readOnly: true                    
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-access