apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 3a9967ad-0ece-4821-8f8f-5d73961d5aba
  labels:
    azure.workload.identity/use: "true"
  name: workload-identity-sa
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-access # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: 3a9967ad-0ece-4821-8f8f-5d73961d5aba # Setting this to use workload identity
    keyvaultName: aks-kv-465        # Set to the name of your key vault
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: application
          objectType: secret  # object types: secret, key, or cert
          objectVersion: ""   # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: title
          objectType: secret  # object types: secret, key, or cert
          objectVersion: ""   # [OPTIONAL] object versions, default to latest if empty          
    tenantId: "6ff1cfba-fc8f-44ff-9478-5e312195584d" # The tenant ID of the key vault 
  secretObjects: # k8s secret
  - secretName: secret
    type: Opaque
    data: 
    - objectName: title
      key: secretkey   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aks-helloworld
  name: aks-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: aks-helloworld
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          valueFrom:
            secretKeyRef:
              name: secret
              key: secretkey
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/opt"
          readOnly: true                    
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: secret-access
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-helloworld
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-helloworld
  namespace: default
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: test1.aks.internal
    http:
      paths:
      - backend:
          service:
            name: aks-helloworld
            port:
              number: 80
        path: /
        pathType: Prefix              